### ISSUE TITLE
Add role information to OSM native reader for relations

### ISSUE THREAD

**Issue by RaczeQ** [duckdblabs/duckdb_spatial#105]
I've tried to implement a full OSM reader for nodes, ways and relations. It seems like I'm not the only one and I've took the liberty to copy a comment from #90 PR:

> @Maxxen  Sorry to write in closed PR but I don't quite get how reading relations would work with this solutions.
> 
> Relations can reference other entities like nodes, ways, and other relations.
> 
> As I understand fields refs is used in ways to get ids of nodes for a given way and for relations to get member objects. The problem is that to properly parse relations we need to know what kind of object is a member and what is its role.
> 
> See this relation: https://www.openstreetmap.org/relation/2730708#map=12/50.6789/17.9061
> 
> It has a bunch of members like:
> - node 128054630 which points to the admin_centre
> - bunch of ways that construct the geometry (outer roles)
> - relation 3172807 which connects it to a subarea
> 
> With current implementation we end up with all ids as numbers in refs array like this:
> ![image](https://github.com/duckdblabs/duckdb_spatial/assets/31594210/fa0fc7cf-40f3-4651-924a-c27c9d7986af)
> which unfortunately makes it impossible to parse any relations that is more complicated than building with multipolygon or donut geometry.
> 

_Originally posted by @ttomasz in https://github.com/duckdblabs/duckdb_spatial/issues/90#issuecomment-1642839322_       

 Based on the original OSM XML content, maybe adding information about the role of the member (`ref` here) will be enough to reconstruct geometries properly (same as `tags` with key=>value, make `refs` a map of id=>role, with the role being optional or null).
![image](https://github.com/duckdblabs/duckdb_spatial/assets/17250607/ae1c6c95-ffd4-41f8-a4ee-24131f827c05)

**Comment by Maxxen** [comment]
Implemented in #108
