### ISSUE TITLE
st_read excel the first row as data 

### ISSUE THREAD

**Issue by wonb168** [duckdblabs/duckdb_spatial#113]
I have two excel, use st_read, one is OK, another read the first row as data rather than header.
Even I copy these sheets to 1 excel, also one is OK, another wrong like this:

sheet0 is OK:
![image](https://github.com/duckdblabs/duckdb_spatial/assets/25274931/f59ffc1b-04ed-4659-adc9-6e592535e6d2)
sheet1 in NOT OK:
![image](https://github.com/duckdblabs/duckdb_spatial/assets/25274931/2c48a45e-db0e-4b31-8afd-3d202a786826)
but, I change the cell B2 to value 123, then also OK,
why?
the attachment is my excel for test, thank you!
[output.xlsx](https://github.com/duckdblabs/duckdb_spatial/files/12318296/output.xlsx)

**Comment by Maxxen** [comment]
Generally it tries to auto-detect whether or not to read the first row as a header, but I'm not sure why it doesn't work as expected In this case. However, I've implemented an option in #114 so that it is possible to force control this behavior.

**Comment by wonb168** [comment]
> Generally it tries to auto-detect whether or not to read the first row as a header, but I'm not sure why it doesn't work as expected In this case. However, I've implemented an option in #114 so that it is possible to force control this behavior.

FROM ST_read('./output.xlsx', open_options = ['HEADERS=FORCE']);

This
Not work for my sheet1 in the attachment excel.

**Comment by nlarusstone** [comment]
This still seems to be broken when reading multi-tab excel files (even when specifying a specific sheet/layer)
