### ISSUE TITLE
Feature: Native GeoJSON copy/table function

### ISSUE THREAD

**Issue by Maxxen** [duckdblabs/duckdb_spatial#12]
We already have a lot of experience using `yyjson` in the json extension, we should be able to port a subset of the functionality from that extension to write a GeoJSON parser. Since we know we're working with a fixed-schema I expect a lot of the complexity can be cut.

**Comment by marklit** [comment]
Is it worth rejecting formats that aren't currently supported? It's not till I try and select from this dataset that I get an exception.

```bash
$ /Volumes/Seagate/duckdb_spatial/build/debug/duckdb -unsigned test.duckdb
```

```sql
LOAD '/Volumes/Seagate/duckdb_spatial/build/debug/extension/spatial/spatial.duckdb_extension';

CREATE TABLE test_geojson AS
SELECT *
FROM st_read('/Volumes/Seagate/open5g_data/Estonia/h3_counts.geojson');
```

```
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
Warning 1: Non closed ring detected. To avoid accepting it, set the OGR_GEOMETRY_ACCEPT_UNCLOSED_RING configuration option to NO
...
```

```sql
.schema
CREATE TABLE test_geojson(sample_cnt VARCHAR, wkb_geometry WKB_BLOB);;
```

```sql
select * from test_geojson;
```

```
libc++abi: terminating with uncaught exception of type duckdb::InvalidInputException: Invalid Input Error: Could not read WKB
Abort trap: 6
```

**Comment by Maxxen** [comment]
GeoJSON should be supported, seems like you need to pass some option? Could you provide me with an excerpt of the dataset?

**Comment by Maxxen** [comment]
Also, I was not aware that invalidinput terminates the process. Ill look into switching to another exception type that produces an error instead.

**Comment by marklit** [comment]
Rename this to `h3_counts.geojson`. GitHub wouldn't allow a .geojson file to be uploaded to a comment.

[h3_counts.txt](https://github.com/duckdblabs/duckdb_spatial/files/11168811/h3_counts.txt)

**Comment by Maxxen** [comment]
Alright, it looks like your geojson is invalid, according to the [geojson spec 3.1.6](https://stevage.github.io/geojson-spec/#section-3.1.6). 
> Polygon
> To specify a constraint specific to Polygons, it is useful to introduce the concept of a linear ring:
> A linear ring is a closed LineString with four or more positions.
> The first and last positions are equivalent, and they MUST contain identical values; their representation SHOULD also be identical.

We should throw an error for this earlier, basically as soon as GDAL warns us. We could also look into adding an option where we use GEOS to try to validate and fix input geometries, although that's probably going to be much slower.

**Comment by marklit** [comment]
That GeoJSON came out of the H3 Python library. Is there a chance something like the above could be treated as valid? It'll load in QGIS without issue.

This is how I built it: https://tech.marksblogg.com/making-heatmaps-python-qgis.html#building-geojson

**Comment by Maxxen** [comment]
The issue is that GEOS, which we currently use for printing WKT, doesn't accept it. But in general we should allow storing invalid geometries that you then can validate/cleanup with something like `ST_IsValid`/`ST_MakeValid`. Once we get #11 we should be able to at least not error out. For what it's worth, if you can avoid printing the geometry you can still probably operate on it, e.g. `SELECT ST_Area(ST_GeomFromWKB(wkb_geometry)) FROM st_read('h3_counts.geojson');` works for me. Although I would be careful as some operations will probably produce garbage if they assume the geometry is valid, like spatial predicates.

**Comment by mrisney** [comment]
Not sure if this is the correct issue thread to bring this up, but could ST_GeomFromGeoJSON,  or JSON geometry fragments could be added to the function request list ?

**Comment by Maxxen** [comment]
Sure, ill put it in the backlog!

**Comment by marklit** [comment]
When I load data into BQ, if there is anything about the geometry that BQ doesn't like (see #73), it'll reject the whole upload. I have a workaround where PostGIS convert the data into GeoJSON, uploads it as a `STRING` and then uses BQ's `make_valid` functionality, which appears to be much more advanced than anything in GEOS or otherwise seen in the open source world, to convert the geometry into a `GEOGRAPHY` data type.

The above works in PostGIS but I'd love to be able to port this to DuckDB as it seems to be at least 4x faster on every workload I've moved over from PostGIS so far.

**Comment by Maxxen** [comment]
Individual geojon fragments can be read since #91

**Comment by Maxxen** [comment]
So we're probably not going to work on this further. 
- You can use the GDAL geojson driver to read both geojson and newline-delimited geojson
- Or you can use the DuckDB json extension the read the main part of the geojson, and then use the `ST_GeomFromGeoJSON` functions to convert the feature geometry fragments into a geometry column. 

Replicating the full on schema inference functionality already present in the json extension would be too much redundant work.

**Comment by bjornasm** [comment]
> So we're probably not going to work on this further.
> 
> * You can use the GDAL geojson driver to read both geojson and newline-delimited geojson
> * Or you can use the DuckDB json extension the read the main part of the geojson, and then use the `ST_GeomFromGeoJSON` functions to convert the feature geometry fragments into a geometry column.
> 
> Replicating the full on schema inference functionality already present in the json extension would be too much redundant work.

It would be really helpful if something about this was put into the documentation. (I would propose something myself but need to wrap my head around it before I feel comfortable adding it myself).

**Comment by Maxxen** [comment]
Done here https://github.com/duckdb/duckdb/pull/24646
