### ISSUE TITLE
Using duckdb spatial in python fails to load

### ISSUE THREAD

**Issue by HurdyGurdy123** [duckdblabs/duckdb_spatial#127]
I'm trying to read parquet files through DuckDB within a python script
On a windows CMD similar to bellow works as expected whereas in  Python the spatial extension appears not to load
Giving Error: 
```
duckdb.CatalogException: Catalog Error: Scalar Function with name st_geomfromwkb does not exist!
Did you mean "stem"?
LINE 1: SELECT airport_name,ST_GeomFromWKB(geometry) AS geom  FROM ......

```
**Simple python script**

```
import duckdb
db = duckdb.connect()
db.execute("INSTALL spatial;")
db.execute("LOAD spatial;")
db.execute("INSTALL parquet;")
db.execute("LOAD parquet;")

def RunTest():
    cursor = duckdb.connect()
    print(cursor.execute('SELECT 42').fetchall())
    print(cursor.execute("SELECT * FROM duckdb_extensions();").fetchall())
    _# Returns ('spatial', False, True, '$HOME\\.duckdb\\extensions\\v0.8.1\\windows_amd64\\spatial.duckdb_extension',_
def RunQuery():
    cursor = duckdb.connect()
    cursor.execute("SELECT airport_name,ST_GeomFromWKB(geometry) AS geom  FROM 'Path\\TO\\Airports.parquet';") # Gives error above
    cursor.execute("SELECT airport_name FROM 'Path\\TO\\Airports.parquet';") # Works
    rows = cursor.fetchall()
    for row in rows:
        print(row[0])


if __name__ == '__main__':
    RunTest()
    RunQuery()

````
NOTE: Airports.parquet was created in QGIS from dummy data it's a small valid geo parquet file for this the data is not important

Tried to change extension_directory  to see if that made a difference  `db.execute("SET extension_directory TO 'F:\\Software\\duckdb_cli-windows-amd64\\extensions';")` in the python script didn't work it did on the CMD version

I'm using Python 3.11.4 on windows

Hopping someone can explain what I need to do for this to work

**Comment by Maxxen** [comment]
Hi! You need to use the same connection to load/install the extension when you perform the queries! E.g. instead of calling `duckdb.connect()` on line 9 to get a new connection, use the same `db` connection you set up previously.
