### ISSUE TITLE
Inconsistent area calculations for polygons with holes

### ISSUE THREAD

**Issue by ToddSmall** [duckdblabs/duckdb_spatial#134]
I've found a variety of inconsistencies in how the spatial extension calculates the area for a polygon with a hole. Here are four representations of the same, colloquially speaking, polygon with a hole. The differences between the representations lie in whether the exterior ring and interior ring are written counter clockwise (CCW) or clockwise (CW).

```
POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0), (0.2 0.2, 0.8 0.2, 0.8 0.8, 0.2 0.8, 0.2 0.2)) -- CCW / CCW
POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0), (0.2 0.2, 0.2 0.8, 0.8 0.8, 0.8 0.2, 0.2 0.2)) -- CCW / CW
POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0), (0.2 0.2, 0.2 0.8, 0.8 0.8, 0.8 0.2, 0.2 0.2)) -- CW / CW
POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0), (0.2 0.2, 0.8 0.2, 0.8 0.8, 0.2 0.8, 0.2 0.2)) -- CW / CCW
```

libgeos's [geosop](https://libgeos.org/usage/tools/#geosop) tool says the area of each of the four polygons is 0.64.

The spatial extension returns the following values for the area when using the `GEOMETRY` type. When the exterior ring and interior ring have different orientations, then the area of the interior ring gets added, rather than subtracted, from the area of the exterior ring, giving an area of 1.36 rather than 0.64.

```
┌─────────────┬────────────────────┬────────────────────────────────────────────────────────────────────────────────────┐
│ description │     st_area(p)     │                                    st_astext(p)                                    │
│   varchar   │       double       │                                      varchar                                       │
├─────────────┼────────────────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ CCW/CCW     │ 0.6399999999999999 │ POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0), (0.2 0.2, 0.8 0.2, 0.8 0.8, 0.2 0.8, 0.2 0.2)) │
│ CCW/CW      │               1.36 │ POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0), (0.2 0.2, 0.2 0.8, 0.8 0.8, 0.8 0.2, 0.2 0.2)) │
│ CW/CW       │ 0.6399999999999999 │ POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0), (0.2 0.2, 0.2 0.8, 0.8 0.8, 0.8 0.2, 0.2 0.2)) │
│ CW/CCW      │               1.36 │ POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0), (0.2 0.2, 0.8 0.2, 0.8 0.8, 0.2 0.8, 0.2 0.2)) │
└─────────────┴────────────────────┴────────────────────────────────────────────────────────────────────────────────────┘
```

The spatial extension returns the following values for the area using the `POLYGON_2D` type. In this case, depending on the orientations, we get four different answers.

```
┌────────────────────┬─────────────────────┬────────────────────────────────────────────────────────────────────────────────────┐
│    description     │     st_area(p)      │                                    st_astext(p)                                    │
│      varchar       │       double        │                                      varchar                                       │
├────────────────────┼─────────────────────┼────────────────────────────────────────────────────────────────────────────────────┤
│ CCW/CCW POLYGON_2D │  0.6399999999999999 │ POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0), (0.2 0.2, 0.8 0.2, 0.8 0.8, 0.2 0.8, 0.2 0.2)) │
│ CCW/CW POLYGON_2D  │                1.36 │ POLYGON ((0 0, 1 0, 1 1, 0 1, 0 0), (0.2 0.2, 0.2 0.8, 0.8 0.8, 0.8 0.2, 0.2 0.2)) │
│ CW/CW POLYGON_2D   │ -0.6399999999999999 │ POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0), (0.2 0.2, 0.2 0.8, 0.8 0.8, 0.8 0.2, 0.2 0.2)) │
│ CW/CCW POLYGON_2D  │               -1.36 │ POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0), (0.2 0.2, 0.8 0.2, 0.8 0.8, 0.2 0.8, 0.2 0.2)) │
└────────────────────┴─────────────────────┴────────────────────────────────────────────────────────────────────────────────────┘
```

When libgeos [calculates the area of a polygon](https://github.com/libgeos/geos/blob/d51982c6da5b7adb63ca0933ae7b53828cc8d72e/src/geom/Polygon.cpp#L445), it subtracts the [_unsigned_ area](https://github.com/libgeos/geos/blob/d51982c6da5b7adb63ca0933ae7b53828cc8d72e/src/algorithm/Area.cpp#L31) of the holes.

You can reproduce my duckdb queries with [duckdb_spatial_area.txt](https://github.com/duckdblabs/duckdb_spatial/files/12775552/duckdb_spatial_area.txt). I did all of the queries using duckdb `v0.9.0`.

**Comment by carlopi** [comment]
I gave a try at fixing this in #135, seemed a nice excuse to take a look under the hood. Super nice code to go through.

**Comment by Maxxen** [comment]
Thanks to both of you!
