### ISSUE TITLE
How to use it

### ISSUE THREAD

**Issue by aborruso** [duckdblabs/duckdb_spatial#22]
Hi, first of all, thank you for this great extension.

Once I have downloaded linux_amd64-extensions.zip, how do I use it?

Unzip and then

```
install 'spatial.duckdb_extension';
load 'spatial.duckdb_extension';
```

Is it right?

Thank you

**Comment by aborruso** [comment]
I have tried, but I have this error

![image](https://user-images.githubusercontent.com/30607/230304540-515bdb9d-f56c-4b22-b56f-4833fd0dc484.png)

**Comment by aborruso** [comment]
Solved using absolute path

**Comment by Maxxen** [comment]
Glad you got it working! I’ll clarify this in the build instructions.

**Comment by aborruso** [comment]
> Glad you got it working! I’ll clarify this in the build instructions.

It's useful to have int the main readme:
- unzip the file;
- run `duckdb -unsigned`
- install using the absolute path (example `install '/home/user/spatial.duckdb_extension';`)
- load it `LOAD spatial;`

Thank you
