### ISSUE TITLE
GEOMETRY fields exported as GPKG not picked up by QGIS

### ISSUE THREAD

**Issue by marklit** [duckdblabs/duckdb_spatial#32]
When I've exported `WKB_BLOB` to GPKG they load without issue in QGIS. But when I export as `GEOMETRY` QGIS fails to detect the field as geometry.

```sql
CREATE TABLE joined1(
  geom GEOMETRY,
  "TR_CODE21" VARCHAR,
  "TR_NAME21" VARCHAR,
  "STE_CODE21" VARCHAR,
  "STE_NAME21" VARCHAR,
  "AUS_CODE21" VARCHAR,
  "AUS_NAME21" VARCHAR,
  "AREASQKM21" DOUBLE,
  "LOCI_URI21" VARCHAR,
  "SHAPE_Leng" DOUBLE,
  "SHAPE_Area" DOUBLE
);;

select count(*) from joined1; # 997

COPY (SELECT *
      FROM joined1)
TO 'joined.gpkg'
WITH (FORMAT GDAL,
      DRIVER 'GPKG',
      LAYER_CREATION_OPTIONS 'WRITE_BBOX=YES');
```

<img width="619" alt="Screenshot 2023-04-06 at 17 44 28" src="https://user-images.githubusercontent.com/359316/230415089-31f5a034-b889-44e8-820c-a6a243e8728e.png">

Is there a way that `GEOMETRY` fields could export the way `WKB_BLOB` fields do so they'll load out of the box in QGIS?

**Comment by Maxxen** [comment]
No, not right now, you need to convert them back into WKB_BLOB with `ST_AsWKB` for GDAL to understand them. It's not a bad idea, I just didn't want to tie the GDAL part too much to the geometry types if #15 goes through, but as that's probably not going to be for a while I'll look into adding a cast or conversion for now.
