### ISSUE TITLE
How to query a layer of OpenFileGDB dataset?

### ISSUE THREAD

**Issue by aborruso** [duckdblabs/duckdb_spatial#45]
Hi,
I have a multilayer OpenFileGDB file. Its name is simple.gdb.
If I run

```
select * from st_read('simple.gdb') limit 10;
```

I have the first ten records. How to read what's the layer name of these 10 records?

How to query only the layer "lorermIpsum"?
I have tried 

```
select * from st_read('simple.gdb lorermIpsum') limit 10;
```

but it does not work.

Thank you

**Comment by blackrez** [comment]
It is related to https://github.com/duckdblabs/duckdb_spatial/issues/36.

**Comment by stev-0** [comment]
It looks to me like it's implemented in the code which calls GDAL:
https://github.com/duckdblabs/duckdb_spatial/blob/main/spatial/src/spatial/gdal/functions/st_read.cpp#L169-L197

but not yet implemented in the duckdb binding code - there is no `layer` option:

https://github.com/duckdblabs/duckdb_spatial/blob/main/spatial/src/spatial/gdal/functions/st_read.cpp#L411

But I'm pretty new to the code so could be wrong.

**Comment by stev-0** [comment]
> It is related to #36.

Not sure it is, in GDAL layers within files are specified as part of the path to the data source, not as an open option.

**Comment by blackrez** [comment]
> > It is related to #36.
> 
> Not sure it is, in GDAL layers within files are specified as part of the path to the data source, not as an open option.

Read this it describe more specially why it reads the first layer : https://github.com/duckdblabs/duckdb_spatial/issues/36#issuecomment-1500277740

**Comment by Maxxen** [comment]
Its an issue on our end, we always open the first layer since we don't have a parameter for the requested layer yet, even though the rest of the code is ready for it.  Ill make a fix for this as soon as I get back on Monday.

**Comment by aborruso** [comment]
It's very important to add support to layer, because a lot of format are dataset, with inside one or more resources: GPKG, FileGDB, OpenFileGDB, ecc..

**Comment by Maxxen** [comment]
As soon as CI passed in #47 I'll merge it.

**Comment by aborruso** [comment]
> As soon as CI passed in #47 I'll merge it.

What will be the syntax to read only the record of one layer?

Will there also be the possibility to read only the list of layers with their geometric typology?

**Comment by Maxxen** [comment]
You can now pass a `st_read('...', layer=<layer_name>)` option to specify which layer.
You can also pass an integer to specify layer by index.
> Will there also be the possibility to read only the list of layers with their geometric typology?

This is a good point, I'll think of adding some sort of meta read function in the future to get metadata from a gdal dataset.
