### ISSUE TITLE
Install fails on last step in Docker container

### ISSUE THREAD

**Issue by mbforr** [duckdblabs/duckdb_spatial#57]
The install is failing on the last step in a Docker container. I am working to create a notebook service that builds DuckDB spatial in it. I get all the way to the last step then hit this issue:

```
#0 87.89 [389/389] Linking CXX static library lib/libgeos_c.a
#0 87.89 ninja: build stopped: subcommand failed.
#0 87.90 CMake Error at /home/jovyan/duckdb_h3/spatial_duckdb/spatial/CMakeLists.txt:48 (message):
#0 87.90   Could not build dependencies project
#0 87.90
#0 87.90
#0 87.91 -- Configuring incomplete, errors occurred!
#0 87.91 See also "/home/jovyan/duckdb_h3/spatial_duckdb/build/release/CMakeFiles/CMakeOutput.log".
#0 87.93 make: *** [Makefile:47: release] Error 1
------
failed to solve: executor failed running [/bin/bash -o pipefail -c GEN=ninja     make release]: exit code: 2
```

The container installs ninja and Open SSL via libssl-dev ninja-build 

Using the base image of jupyter/datascience-notebook which has the nuance of the home directory being /home/jovyan

I tried to manually set the CMAKE_BINARY_DIR since it looks like it fails on this step as indicated by the error: https://github.com/duckdblabs/duckdb_spatial/blob/main/spatial/CMakeLists.txt#L48

**Comment by Maxxen** [comment]
Thanks for raising this issue!
I don't think you need to set CMAKE_BINARY_DIR manually, it should be automatically set to the build directory.
It fails when building the dependencies subproject, but it doesn't seem like the error is very useful (its just empty...).
I'll try to reproduce by building the docker container myself. Hold on.

**Comment by Maxxen** [comment]
I suspect you're missing `sqlite3`? Sadly we still need a sqlite3 executable compiled for the host system during building. We should be able to patch PROJ to circumvent this in the future though.

**Comment by mbforr** [comment]
that was the issue! i saw it in the output but then it looked like it had resolved itself. now just running into issues loading and installing it in the context of the container in the notebook. the load step works fine but install says it can't find the same file.

**Comment by Maxxen** [comment]
Hmm, you should be able to pass the absolute path to the extension file when running the `INSTALL` command. Should be putputted to bulld/release(or debug)/extension. Othwerwise duckdb looks for extensions in "~/.duckdb/extension/<duckdb version>/<architecture>/". E.g. For me its "~/.duckdb/extension/v0.7.1/osx_arm64/"

**Comment by mbforr** [comment]
Yeah because of the folder structure but got that sorted and working great now! Thanks for the help!
