### ISSUE TITLE
Provide spatial extension description and update installed status

### ISSUE THREAD

**Issue by RandomFractals** [duckdblabs/duckdb_spatial#64]
Currently this duckdb extension shows `NULL` in the `installed` status after installing and loading it. Try:

```sql
install spatial;

load spatial;

select * from duckdb_extensions();
```

Also, it doesn't provide extension description like other native and 3rd party duckdb extensions do.

![duckdb-spatial](https://user-images.githubusercontent.com/656833/235668196-72c2e6c1-c9f0-4e55-8f8d-5a39a05683a9.png)

**Comment by Maxxen** [comment]
This has been fixed.
