### ISSUE TITLE
ST_ReducePrecision support?

### ISSUE THREAD

**Issue by marklit** [duckdblabs/duckdb_spatial#81]
Paul added this to PostGIS back in December 2020. It uses GEOS 3.9+.

Anyone installing the `postgresql-15-postgis-3` Ubuntu package should have it but the above package was built with an older version of GEOS. To make matters worse, PostGIS will report the version of GEOS it finds on your machine, not the version it was built with which causes a lot of confusion when getting `Precision reduction requires GEOS-3.9 or higher` when using `ST_ReducePrecision` and `SELECT PostGIS_GEOS_Version();` returns `3.11.1-CAPI-1.17.1`.

Given your extension seems to be at least 4x quicker with most workloads, it would be nice to see `ST_ReducePrecision` added at some point so I could migrate some more workloads.

**Comment by Maxxen** [comment]
Implemented in #95

**Comment by marklit** [comment]
Fantastic. Thank you.
